### ISSUE TITLE
About systems & system settings 

### ISSUE THREAD

**Issue by Nakamerica** [Aryan20/Logomenu#10]
Hi, don't you think having both the "System Settings" and the "About System" buttons is a bit redundant? Would be a bit more polished to only have one of those two, in my opinion. Please consider this, thanks.

**Comment by Aryan20** [comment]
Yeah, I never actually thought of that, and what you said does seem right, I will think about it and maybe it will be gone in the next version

**Comment by Nakamerica** [comment]
yeah, i think it would make sense to remove the 'System settings' button since:

a. About settings leads to system settings anyways and 
b. the settings button is available in the system controls tab in  the far right of the top panel. 

Thanks for considering the suggestion :)

**Comment by Aryan20** [comment]
Suggestion Implemented :)
