### ISSUE TITLE
Issue with Logomenu settings layout

### ISSUE THREAD

**Issue by Nakamerica** [Aryan20/Logomenu#11]
Hi, I recently installed this extension and noticed a small issue, opening the extensions' settings from the Gnome-Extensions app leads to the settings page having a very weird configuration (short screencast attached). However, when the settings are opened from the gnome extensions website, the layout is completely normal. 

My system info is as attached:  

  ```
                  ./o.                  nakamerica@anmol 
                   ./sssso-                ---------------- 
                 `:osssssss+-              OS: EndeavourOS Linux x86_64 
               `:+sssssssssso/.            Host: VivoBook_ASUSLaptop X412DA_X412DA 1.0 
             `-/ossssssssssssso/.          Kernel: 5.16.10-arch1-1 
           `-/+sssssssssssssssso+:`        Uptime: 21 mins 
         `-:/+sssssssssssssssssso+/.       Packages: 1099 (pacman), 7 (flatpak) 
       `.://osssssssssssssssssssso++-      Shell: zsh 5.8.1 
      .://+ssssssssssssssssssssssso++:     Resolution: 1920x1080 
    .:///ossssssssssssssssssssssssso++:    DE: GNOME 41.4 
  `:////ssssssssssssssssssssssssssso+++.   WM: Mutter 
`-////+ssssssssssssssssssssssssssso++++-   WM Theme: Colloid-teal-dark 
 `..-+oosssssssssssssssssssssssso+++++/`   Theme: Colloid-teal-dark [GTK2/3] 
   ./++++++++++++++++++++++++++++++/:.     Icons: Colloid-dark [GTK2/3] 
  `:::::::::::::::::::::::::------``       Terminal: gnome-terminal 
                                           CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8) @ 2.100GHz 
                                           GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
                                           Memory: 3081MiB / 5943MiB 

```

https://user-images.githubusercontent.com/88226614/154792635-18160c69-ee84-4d0e-9203-b4b866f2c4e3.mp4

A short screencast of the issue ^

I would appreciate it if this is looked at.

**Comment by Aryan20** [comment]
I'm sort of aware of this issue, I saw it in the latest build of GNOME OS Nightly, if you go to the overview page, you will most likely find that all the settings are there, it's just very very large. Thus I updated it on GitHub to have a scroll feature to limit its size, but I didn't know that version of GNOME has made its way down to rolling releases ( I miss using those ). I would suggest you to try out the latest version available on Github and do a log out and log in or restart.  and please report here if it works :)

**Comment by Nakamerica** [comment]
> I'm sort of aware of this issue, I saw it in the latest build of GNOME OS Nightly, if you go to the overview page, you will most likely find that all the settings are there, it's just very very large. Thus I updated it on GitHub to have a scroll feature to limit its size, but I didn't know that version of GNOME has made its way down to rolling releases ( I miss using those ). I would suggest you to try out the latest version available on Github and do a log out and log in or restart. and please report here if it works :)

thank you, it's perfectly fine now. My bad for not using the latest version before reporting an issue. thanks for the extension.

**Comment by Aryan20** [comment]
Thanks, and no issues, will release the latets version on Extension store soon
