### ISSUE TITLE
Custom Icons?

### ISSUE THREAD

**Issue by LES-11** [Aryan20/Logomenu#16]
Will you be adding support to upload custom icons?

**Comment by Aryan20** [comment]
Yes! It's on my radar, I'm just unable to get the time needed to implement it, but it will surely be implemented, either by me or someone else.

**Comment by cristian-enve** [comment]
Hi! I've just added a commit with icons for each button. please feel free to review the code.

**Comment by Aryan20** [comment]
@haydenjames Hey! No, unfortunately, I didn't get the time to implement it. You can add your own svg by placing it in the resource folder in the extension folder and adding the entry in constants.js, but there is no specific setting for it currently.

**Comment by halfmexican** [comment]
I'm going to try to take over this issue and submit a PR

**Comment by Aryan20** [comment]
@halfmexican Assigned you
