### ISSUE TITLE
xkill complaints

### ISSUE THREAD

**Issue by yavko** [Aryan20/Logomenu#20]
Hello I use wayland, so `xkill` only works on `xwayland` apps, could you implement something that works on `wayland`? Also you cant cancel `xkill` with `esc`, so something that is better implemented would be better in every way IMO.

**Comment by Aryan20** [comment]
Hey, I wasn't able to find any replacement of xkill for Wayland, hence there's an option to disable it in extension preferences.
If in future someone is able to implement something like that for Wayland then maybe I will put that instead of xKill, but for now there's no solution.

**Comment by yavko** [comment]
> one is able to implement something like that for Wayland then maybe I will put that instead of xKill, but for now there's no solution.

Thats fair, I think I've thought of a way to do, maybe there could be like a popup menu with all the open apps, and if you clicked one it would kill it? Idk this is a bit too complex.

**Comment by Aryan20** [comment]
Yeah, there can be some solutions but they will be too complex for this project at the current stage :)
