### ISSUE TITLE
[Feature request] Asahi Logo

### ISSUE THREAD

**Issue by cmalvi** [Aryan20/Logomenu#27]
As title, would be cool to select the asahi logo, here the icon from official repo

https://github.com/AsahiLinux/artwork/tree/main/logos

**Comment by Aryan20** [comment]
Done :)

**Comment by cmalvi** [comment]
Thanks! :) do you suggest to update manually form here or will be updated from extension soon?

**Comment by Aryan20** [comment]
Hey, thanks for your remarks :) 
I would suggest installing from the extension store as I will be updating it in a few days, but using from source is also fine.
