### ISSUE TITLE
Lastest Version (11) on extension store doesn't start [16-05-2022]

### ISSUE THREAD

**Issue by cmalvi** [Aryan20/Logomenu#28]
Error shown:

`Constants.DistroIcons[iconIndex] is undefined`

**Comment by Aryan20** [comment]
Hey, thanks for your patience! Is the issue still around?

**Comment by cmalvi** [comment]
I’m not sure about. On one pc no problem but on my laptop I’ve reinstalled it from source. Maybe not but if you have time try to check. Thanks :)

**Comment by Aryan20** [comment]
The issue doesn't seem to be in code, maybe something went wrong on your side, try using the one on the extensions store, it should hopefully work fine. Thanks :)

**Comment by cmalvi** [comment]
All updated from extension store and now works with no problem, thank you :)

**Comment by Aryan20** [comment]
Nice! :)
