### ISSUE TITLE
Wrong text in Italian

### ISSUE THREAD

**Issue by XargonWan** [Aryan20/Logomenu#33]
"Force quit application" is written as "Forza chiusura applicazionw" insead of "Forza chiusura applicazion**e**", the last **w** should be **e**.

![Schermata del 2022-08-31 17-36-12](https://user-images.githubusercontent.com/6771419/187719963-66813884-196d-4ad3-b23b-be9b675b8a0f.png)

**Comment by Aryan20** [comment]
Hey, thanks for the heads up, will update it

**Comment by Aryan20** [comment]
Fixed :)
