### ISSUE TITLE
Not working with GNOME 43.

### ISSUE THREAD

**Issue by scottbeamer** [Aryan20/Logomenu#36]
I'm running GNOME 43 beta.  The final release is out on September 21.  Could you update this extension to work with GNOME 43 at your earliest convenience?  Thank you.

**Comment by Aryan20** [comment]
Hey, yeah, I actually updated the extension when GNOME 43 Beta first came out, but didn't get time to update it upstream. I will update it soon :)

**Comment by Aryan20** [comment]
Fixed, I would appreciate it if you try it and tell if you face any errors. :D
