### ISSUE TITLE
Custom command for extension application

### ISSUE THREAD

**Issue by RobOT05442309** [Aryan20/Logomenu#40]
Hello,

I would like to request for a feature if possible.

When clicking on "Extensions" into the menu, it bring back the default's gnome manager, I was wondering if there will be a way to add a custom command just like `gnome-terminal` and `gnome-software`.

```sh
# Custom command could be:
flatpak run com.mattjakeman.ExtensionManager
``` 
Edit: Update command since I make a double `flatpak run` command...

*For the background story:* 

I'm using the flatpak application "Extension manager" (https://flathub.org/apps/details/com.mattjakeman.ExtensionManager) to handle gnome shell extensions and installation instead of default gnome's one (easier to install extensions when using flatpak browser that does not currently support chrome's gnome shell extension).

There is no rush about it, I just wanted to know if you could make it or not at all.

Anyway, thanks you for your work and time on this extension!

**Comment by Aryan20** [comment]
Hey, 
Thanks for using my extension and for your kind remarks!
I have already added support for the application you shared, the extension checks if you have the default GNOME Extensions application installed or not, if not then it searches for the "Extension manager" application and launches that if installed.
It could be that you have both applications installed simultaneously. Can you check if it works with the default one removed? :)

**Comment by RobOT05442309** [comment]
Thanks for your quick feedback!

Well, you're right, I have both of them (I keep the original one hidden from application grid 'just in case' something goes wrong with the flatpak, not maintained anymore or otherwise and/or since I don't know how extensions updates are handles from any of this applications), so I have uninstall the `gnome-extensions-app`, reload the shell but sadly now nothing happened when I click on `Extensions` in the submenu, I'll do a reboot to check if it's working after and edit this post to give you a feedback!

Even if it worked, do you think that this feature request could still be implemented or it will be too much work from your side combining the custom command and the check of available application on the system?

**Comment by Aryan20** [comment]
Hey, thanks for all your input!
It is weird, it should have worked, as it did when I tried it on a virtual machine. But no issues, I will add a toggle to switch between the default one and the "Extension Manager".
Regarding the french translation, thanks for pointing it out, will be updating it soon :)

**Comment by Aryan20** [comment]
I have added the option to change the Extension app. You can try it out by either downloading the code from here and installing it or you can wait for the next version release, whenever that happens :)

**Comment by RobOT05442309** [comment]
Thanks you for the quick fix, I'll test it when a new release will update and report here (even if the issue is close).

I don't know on how system you've try it on VM but I use Fedora 36 if that can help for anything.

Additionally I've made the French translation for the new added strings if you want to add them at some point:

```
# From line 100 to 110

#: PrefsLib/adw.js:152 PrefsLib/gtk.js:186
msgid "Preferred Extensions Application"
msgstr "Application d'extension préférée"

#: PrefsLib/adw.js:158 PrefsLib/gtk.js:193
msgid "GNOME Extensions"
msgstr "Extensions de GNOME"

#: PrefsLib/adw.js:159 PrefsLib/gtk.js:194
msgid "Extensions Manager"
msgstr "Gestionnaire d'extensions"
```

Have a nice day!

**Comment by Aryan20** [comment]
Hey, thanks for your work!

I will definitely be adding your changes to the translation.

Have a great day too! :D
