### ISSUE TITLE
Position determination?

### ISSUE THREAD

**Issue by samirsth** [Aryan20/Logomenu#41]
Needed absolute left position no matter what

**Comment by Aryan20** [comment]
Can you be more elaborate?

**Comment by samirsth** [comment]
Like other extensions can’t mess with the position of it 
I need the logo in absolute left corner

**Comment by Aryan20** [comment]
Which extension is messing with its position?

**Comment by samirsth** [comment]
Username and Hostname to panel

**Comment by samirsth** [comment]
It look like this when I turnoff and on the extension. (I want like this)
 ![image](https://user-images.githubusercontent.com/87382409/201051751-1dd0ac1c-3c0b-4ec9-99b6-0c064c57d9a3.png)

But whenever I logout or reboot it look like this (I don't want this)

![image](https://user-images.githubusercontent.com/87382409/201052182-9b3c9c74-3430-42bb-af2c-11a136b52bb3.png)

**Comment by Aryan20** [comment]
As far as I can check, both extensions are contesting for the left-most corner, and are assigned that by the GNOME Shell and thus I don't think I have any control over that, maybe there could be some way but if other extensions also use it then it is of no use. So, TLDR: For now I don't think there is any solution to do it. Maybe you can try changing the other extension's position in the code. Have a nice day :)

**Comment by samirsth** [comment]
Okay! Thank you for you assistance. 
Have a great day!❤️
