### ISSUE TITLE
[Feature request] Option to add custom application like system monitor

### ISSUE THREAD

**Issue by dalpatsingh-jabsainfotech** [Aryan20/Logomenu#42]
I always go to the logo menu naturally to launch the system monitor app, unfortunately, have to realize that it doesn't have the option for that. It would be great if custom application support is added. 

BTW Thanks for the extension, it is wonderful.

**Comment by Aryan20** [comment]
Hey, that is a good feature to add. I will check for the best way to implement it and would probably work on it after my exams. 
Also, thanks for your kind remarks :)

**Comment by dalpatsingh-jabsainfotech** [comment]
Opened a [PR](#43 ), You may want to merge it. Working well on ubuntu 21.10

![image](https://user-images.githubusercontent.com/119921695/207794953-4dd2e421-5eb2-400e-8afa-285b9992b734.png)

**Comment by Aryan20** [comment]
Hey, thanks for your work! But, I was instead thinking of adding a custom option, where the user can specify some custom apps with custom names. This way it will be much more flexible.

**Comment by dalpat** [comment]
Sure, please keep both the system monitor and the custom option. or else a better option would be to provide more than one custom option.

**Comment by Aryan20** [comment]
Yes, for now I'm adding 2 options, maybe in future I will add more

**Comment by Aryan20** [comment]
Added
