### ISSUE TITLE
Logo menu cannot launch flatpak applicaions

### ISSUE THREAD

**Issue by OulipianSummer** [Aryan20/Logomenu#49]
I have blackbox terminal installed on my system using Flatpak. When I input this string into the terminal text box in Logo Menu, it fails to launch: `flatpak run com.raggesilver.BlackBox`.

Even removing the `flatpak run` portion of the command does not work.

The error message is always the same: `Execution of  "<the command> failed": command not found`.

I'm not sure how exactly Logo Menu executes these commands or what kinds of commands it is expecting to see in order to launch an application.

**Comment by Aryan20** [comment]
Hey! Seems like the extension is unable to handle flatpack commands at the moment. Thanks for bringing it up. Will see what can be done.

**Comment by Aryan20** [comment]
So from what I saw, the way the extension works at the moment, it can either launch a flatpak application or a native application. I'm considering doing some extensive changes to the extension as part of the GNOME 45 release or later. Will probably add an option to switch between them then.

**Comment by OulipianSummer** [comment]
Interesting! I guess I must have been using the wrong string. Out of curiosity, what inputs worked for you during your tests? And yeah, a toggle or selection for the type of application or command you want to run would make sense for this scenario, especially since command syntax can be so different across distros or app managers.

**Comment by Aryan20** [comment]
No, I meant if I add the support in the backend. 
Currently, it is only going to open native applications. For Flatpak the backend code is different, and you need to provide a desktop file name, which is quite complicated for any user. I will have to look more into it to make it less complicated and yeah, there will be a toggle to switch between them if and when it is implemented.

**Comment by Aryan20** [comment]
Fixed!
