### ISSUE TITLE
xkill doesnt work in wayland 

### ISSUE THREAD

**Issue by KnightKrusty** [Aryan20/Logomenu#5]
"Force quit app" option uses xkill which doesnt work in Wayland, would be cool to have different implementation for Wayland systems.

**Comment by Aryan20** [comment]
Hey, sorry for late reply, I know xkill doesn't work on Wayland, that's why I put the option to disable it in settings, altho if I find a replacement for that which works on Wayland, then I will switch 🙂

**Comment by KnightKrusty** [comment]
Looked into the whole wayland thing and why xkill is not working, seems like there wont be any alternative coming soon to wayland.

**Comment by Aryan20** [comment]
> Looked into the whole wayland thing and why xkill is not working, seems like there wont be any alternative coming soon to wayland.
> 

Yup, tbh, system monitor or terminal commands is a better choice to kill a process anyway :)
