### ISSUE TITLE
Adding new OS logo but get a red small icon in the Settings instead of grey one

### ISSUE THREAD

**Issue by D3vil0p3r** [Aryan20/Logomenu#50]
Hey @Aryan20 thank you for your project.

I'm trying to add the following svg file
![athena-logo-menu](https://github.com/Aryan20/Logomenu/assets/83867734/70b44d12-2e30-4ad9-8883-956dfd572338)

as `athena-logo-symbolic.svg` in the `Resources` folder and `hicolor/16x16/actions` folder as 496x496 (like all the images). When I go to the Settings of the extension, the icon of the OS appears red (look the last at right)
![image](https://github.com/Aryan20/Logomenu/assets/83867734/c535937d-c2d5-4498-883d-6263459aca95)

Furthermore, despite all the icons are colored by #cccccc as mine, when they are applied on the top bar, they become all white (I think it is expected)
![image](https://github.com/Aryan20/Logomenu/assets/83867734/a1906c41-751d-4558-a139-1b00d9423094)

my icon instead keeps the #cccccc grey color
![image](https://github.com/Aryan20/Logomenu/assets/83867734/0460395f-4611-4b99-a216-b3c546b760fd)

How can we fix these two issues?

**Comment by Aryan20** [comment]
Hey! This is weird. But I have experienced it before. For example, the Ubuntu logo appears weird for some reason. Did you try to use the default icon and theme instead of custom?

**Comment by D3vil0p3r** [comment]
> Hey! This is weird. But I have experienced it before. For example, the Ubuntu logo appears weird for some reason. Did you try to use the default icon and theme instead of custom?

Yes, the icons already implemented work well. I would like to implement the proposed one for [Athena OS](https://www.athenaos.org] Linux distro.

**Comment by Aryan20** [comment]
No, I meant to try using the default GNOME Icon theme and Application, Shell theme. In your screenshot, it appears you have modified your distro.

**Comment by D3vil0p3r** [comment]
Now I tested on Vanilla Arch Linux with GNOME DE (both on Wayland and Xorg) and when I implement the owl grey icon above, the result is the following:
![image](https://github.com/Aryan20/Logomenu/assets/83867734/f81b1205-36f0-477f-add0-ed3e645e267c)

So, on settings, the icon now is seen as that "yellow" color.

**Comment by Aryan20** [comment]
Looks like the Ubuntu bug. Will check it

**Comment by Aryan20** [comment]
Hey! So it is most probably due to bad svg. I checked the Ubuntu one and it had some wrong tags, and is now fixed. Your logo is an image encoded in an SVG, hence higher chances of failure.
Do you have a pure SVG version of the logo?

**Comment by D3vil0p3r** [comment]
No... How can I know what are the wrong tags?

**Comment by Aryan20** [comment]
I don't work with SVGs much but there was a style statement which shouldn't have been there after recolouring, so removed that. In your case it is an image, not an SVG, so don't know about that.

**Comment by halfmexican** [comment]
can this be closed?  users can just add non-svg icons now

**Comment by Aryan20** [comment]
@halfmexican Yes, thanks for the reminder.
