### ISSUE TITLE
Drastic change of icon size

### ISSUE THREAD

**Issue by GoldenMelky** [Aryan20/Logomenu#54]
when i increase the icon size from 24 to 25px it drastically change size
[Video del 2023-09-07 12-57-42.webm](https://github.com/Aryan20/Logomenu/assets/83531180/2515dfae-30f9-4a7c-9b0c-659136285a97)

**Comment by Aryan20** [comment]
Hey! Thanks for reporting. I am unable to reproduce this behaviour. 
Can you check how other icons behave? Is it only with the apple one or do others also drastically change?

**Comment by GoldenMelky** [comment]
nope, it's just the apple logo

**Comment by Aryan20** [comment]
Then it could be an issue with the icon pack you are using. The first icon is taken from the icon pack, in this case, it is the Apple logo.

**Comment by GoldenMelky** [comment]
Ohh, okay. thanks!

**Comment by Aryan20** [comment]
No problem :)
