### ISSUE TITLE
[Feature Request] Add BazziteOS and Steam Deck Icons From Bazzite Logo Menu Fork

### ISSUE THREAD

**Issue by KaiserCalm** [Aryan20/Logomenu#57]
The Icons:
- [Bazzite Colored](https://github.com/KyleGospo/Logomenu/blob/main/Resources/bazzite-logo.svg)
- [Bazzite Mono](https://github.com/KyleGospo/Logomenu/blob/main/Resources/bazzite-logo-symbolic.svg)
- [Steam Deck Colored](https://github.com/KyleGospo/Logomenu/blob/main/Resources/steam-deck-logo.svg)
- [Steam Deck Mono](https://github.com/KyleGospo/Logomenu/blob/main/Resources/steam-deck-logo-symbolic.svg)

These icons would make a great addition for people using Logo Menu on these OSes. As long as the license and fork maintainers allow it.

**Comment by Aryan20** [comment]
Hey! Seems like their fork of Logo Menu would be preinstalled in their OS with these logos built-in, so I don't think this needs an upstream change. If the maintainers want, they can open a PR to get these upstream, and I would be happy to consider.

**Comment by KaiserCalm** [comment]
Hello, I use multiple versions of their OS on multiple devices and only the Steam Deck version comes with that fork of the Logo Menu, all the other ones need this version manually installed, that's why I thought that it would be nice if the logos were included here too.

**Comment by Aryan20** [comment]
Okay, I'll look into that.
