### ISSUE TITLE
Missing files from Github downloads

### ISSUE THREAD

**Issue by getzze** [Aryan20/Logomenu#60]
Hi,
I don't know why but `selection.js` and `display_module.js` are missing from the sources (.tar.gz and .zip) and the built extension in the Github releases page. I am using the source for installing the extension in [Arch Linux](https://aur.archlinux.org/packages/gnome-shell-extension-logo-menu), but the installation is broken because of these missing files.

**Comment by Aryan20** [comment]
Hey! If you are using the releases page for extension source code, but the make file of the latest branch, then it will be causing issues. That is because the files were added in 21.6 meanwhile latest release (on GitHub) is 21.4. 
I will update the release.

**Comment by getzze** [comment]
Thanks, you are right it seems it was a mismatch between the makefile version and the release source.
