### ISSUE TITLE
Updated Debian Logo

### ISSUE THREAD

**Issue by codex78** [Aryan20/Logomenu#65]
Hi friend @Aryan20,
Please, update the official Debian Logo. I attached the file to you :)

![debian-logo](https://github.com/Aryan20/Logomenu/assets/39781535/d8208c04-1dd9-4d97-9463-4e7aa8784084)

...take a look how to look this logo in my system (without that ugly grey circle background)

![Captura desde 2023-12-30 13-41-40](https://github.com/Aryan20/Logomenu/assets/39781535/a4ef381a-4d9a-43ca-84ad-bdb382c00b48)

Thanks for your attention 👍🏼 

...if you like, i can make the change and send a pull request with it.

Best regards!

**Comment by Aryan20** [comment]
Done!
