### ISSUE TITLE
Framework Logo

### ISSUE THREAD

**Issue by 9thdude** [Aryan20/Logomenu#70]
Could we get the Framework computers logo added? I'd submit a PR, but I'm no good at making SVGs so I hope this is a good halfway point to getting it added.

![framework_logo_recolored_resized_white](https://github.com/Aryan20/Logomenu/assets/60372869/7335975f-5f26-4594-b2fe-1b9ae6a89951)
![framework_logo_recolored_resized](https://github.com/Aryan20/Logomenu/assets/60372869/40fc300e-b1f1-448a-973c-00d794caef40)

**Comment by Aryan20** [comment]
Hey! Framework is a hardware only manufacturer, hence can't be added to the menu.
But, we recently added an option to choose your own logo in the menu settings. There you can easily use the png files as well.

Thanks for your interest in the menu :)
