### ISSUE TITLE
Ubuntu 22 (Gnome 42) dropped?

### ISSUE THREAD

**Issue by in4matix** [Aryan20/Logomenu#79]
I am really sad that you have decided not to implement future updates for Ubuntu 22.04 LTS...

**Comment by in4matix** [comment]
I understand your predicament. The later version looks a lot more polished than version 18. My organization is with Ubuntu 22 LTS and we have no intention to change to Gnome 46 soon as there are and will be issues for quite some time still with Gnome 46 and major issues with Ubuntu 24.

**Comment by in4matix** [comment]
@Aryan20 , I have Gnome 46 (Ubuntu 24) in a VM now, and I must admit that, like you said, there are not really a huge difference between LM for G42 and for G46, so if you want to close this, that's okay. Thank you for this awesome extension.

**Comment by Aryan20** [comment]
Hey, thanks for your kind words 😃
Sure, closing the issue, will try to port any major changes if we get them to the older version.
