### ISSUE TITLE
Selecting the white AlmaLinux icon gives you the color Manjaro icon instead

### ISSUE THREAD

**Issue by scottbeamer** [Aryan20/Logomenu#8]
AlmaLinux 8.5
GNOME 3.32.2
Also, what appears to be the color AlmaLinux icon is just black.

![wrong icon](https://user-images.githubusercontent.com/62769036/151645811-d3dd498e-6bef-45f6-b0f0-3c8b99670369.png)

**Comment by Aryan20** [comment]
That is very weird. Does other distro logo work fine? Also please try to change your icon pack to the default one and check if the problem persists.

**Comment by scottbeamer** [comment]
> That is very weird. Does other distro logo work fine? Also please try to change your icon pack to the default one and check if the problem persists.

No. some of the others were messed up, also.   However, I did as you suggested and switched to the default GNOME icons, and that fixed the problem with the white logo.  That shouldn't make a difference, though.

The color version of the logo still appears black, however, and that's the one I really want to use.

**Comment by Aryan20** [comment]
Sorry for the late reply, I forgot to check due to some work.
I never had this issue, will have to try on your GNOME version to check what is the issue. 
Can I ask what Icon Pack are you using?

**Comment by scottbeamer** [comment]
> Can I ask what Icon Pack are you using?

Adwaita. The GNOME default icons.

**Comment by Aryan20** [comment]
@scottbeamer The issue should be fixed now, try to uninstall the current version and then, manually install by cloning the latest version from GitHub.
The issue occurred as Gnome was unable to render the CSS part (which gave color) in SVG, so I removed the CSS part and gave color attributes in SVG syntax. Had to install AlmaLinux myself to properly test :)

**Comment by scottbeamer** [comment]
> The issue occurred as Gnome was unable to render the CSS part (which gave color) in SVG, so I removed the CSS part and gave color attributes in SVG syntax.

I have no idea what this means, but thanks for your help.

It's working now.

![image](https://user-images.githubusercontent.com/62769036/153269655-3b6fbab9-6602-49ac-879b-793e10079bf2.png)

**Comment by Aryan20** [comment]
> I have no idea what this means, but thanks for your help.
> 


lol ok, thanks for reporting the issue
