### ISSUE TITLE
Wider menu request

### ISSUE THREAD

**Issue by matt-matt1** [Aryan20/Logomenu#81]
I have an OSX computer that I often use it along with this Ubuntu computer.  I like the aspect ratio with the apple menu on OSX (it seems the words "About This Mac" could be written twice inline, within the menu).  I suggest that the menu on Gnome appear wider as the OSX menu.

**Comment by Aryan20** [comment]
Am late to reply to this, earlier I tried something like that but at the moment I believe letting GNOME decide the width based on the widest entry is the way to proceed. The apple menu is mainly wider to have gap between the shortcuts label and item label, which we don't have in our case.
