### ISSUE TITLE
 Error appears after reinstalling OS

### ISSUE THREAD

**Issue by Amir000001** [Aryan20/Logomenu#82]
I reinstalled the OS and installed the extension and the following error started appearing; before the reinstallation, the extension worked without errors. I decided that I did something wrong and reinstalled it again, but the error did not go away

![Снимок экрана от 2024-07-06 21-48-38](https://github.com/Aryan20/Logomenu/assets/48696044/05537e92-5838-4dff-851b-026bdfb46ff8)

**Comment by Aryan20** [comment]
Can you share some more info, such as the extension version and your OS details as well?
Thanks

**Comment by Aryan20** [comment]
Also, are you using it just in English or does your system use a different language? From the screenshot, it looks like English but this specific line error is usually caused due to translation

**Comment by Amir000001** [comment]
# Отчет о подробностях системы
---

## Подробности отчета
- **Дата создания:**                               2024-07-07 00:32:41

## Аппаратная информация:
- **Модель оборудования:**                         Lenovo Lenovo Legion 5 15ARH05H
- **Память:**                                      16,0 ГиБ
- **Процессор:**                                   AMD Ryzen™ 7 4800H with Radeon™ Graphics × 16
- **Графика:**                                     AMD Radeon™ Graphics
- **Графика 1:**                                   NVIDIA GeForce RTX™ 2060
- **Ёмкость диска:**                               (null)

## Программная информация:
- **Версия прошивки:**                             FSCN14WW
- **Название ОС:**                                 Fedora Linux 40 (Workstation Edition)
- **Сборка ОС:**                                   (null)
- **Тип ОС:**                                      64-бит
- **Версия GNOME:**                                46
- **Оконный интерфейс:**                           Wayland
- **Версия ядра:**                                 Linux 6.9.7-200.fc40.x86_64

**Comment by Amir000001** [comment]
system language Russian

**Comment by Amir000001** [comment]
After changing the system language everything worked, thank you)

**Comment by Aryan20** [comment]
Got it, there was an error with the Russian translation causing the issue. It is fixed but not yet released. Will release new version soon.
